#!/bin/bash

# This lines call the CIVET pipeline in the VM with all the files at the
# /vagrant common directory

topdir=/vagrant/CIVET_Hypno
source /usr/local/civet-2.1.1-binaries-ubuntu-18/Linux-x86_64/init.sh

ls *t1.mnc | parallel \
/usr/local/civet-2.1.1-binaries-ubuntu-18/Linux-x86_64/CIVET-2.1.1/CIVET_Processing_Pipeline  \
-sourcedir $topdir/final -targetdir $topdir/result -prefix Hyp -N3-distance 0 -lsq12 -mean-curvature \
-mask-hippocampus -resample-surfaces -correct-pve -interp sinc -template 0.50 -thickness tlink 10:30 \
-area-fwhm 0:40 -volume-fwhm 0:40 -VBM -surface-atlas AAL -granular -run {}
